spring.application.name=groceries

# ===============================
# CONFIGURAÇÕES DO BANCO DE DADOS
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/groceries
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURAÇÕES DO JPA / HIBERNATE
# ===============================
# Desativa a criação de tabelas pelo Hibernate (o Flyway vai cuidar disso)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.format_sql=true

# ===============================
# CONFIGURAÇÕES DO FLYWAY
# ===============================
spring.flyway.enabled=true
# (Opcional) Permite que o Flyway limpe e recrie o banco, útil apenas em ambiente de DEV
spring.flyway.clean-disabled=true